### ISSUE TITLE
Topo Channel Unit Schema: Null Tier1/Tier 2 types

### ISSUE THREAD

**Issue by volkcj** [SouthForkResearch/CHaMP_Metrics#100] opened 2017-10-11 23:50 UTC
Similar to the Aux Channel Unit schema, there are null Tier1/Tier2 types for some channel units with metrics. 2015-2016 are blank for all years, and there's less of a problem for 2011-2014

e.g. VisitID 3225

**Comment by philipbaileynar** [comment] 2017-10-16 18:19
This was caused by two inter-related problems. First, the topo metrics were producing XML files with zeroes in the tier 1 and tier 2 names when there were no occurrences of a particular type. This was fixed with commit efbe1382b26c6a39a2cd34dbee7e7e14d124e00c.

Second, the Workbench would bail on downloading tier 1 and 2 metrics when it came across this zero value in the data from the API and couldn't verify that it is a valid channel unit tier name. So metric values were actually getting calculated, but the names were wrong and this was preventing the Workbench from downloading the values.

Should be fixed for next full run.

**Comment by volkcj** [comment] 2017-10-20 22:32
no tier 1/tier 2 in QA-Topo Channel Unit Metrics schema for visit 3225.  please confirm this visit works.  I can't get postman to work right now (it's not authorizing)..

**Comment by MattReimer** [comment] 2017-10-26 16:33
Here's what I seein postman from the `QA - Topo Channel Metrics` schema

#### <https://api.CHaMPMonitoring.org/api/v1/Visit/metricschemas/QA - Topo Channel Metrics/metrics/a12a2ffe-ff83-4ee4-90d7-1ac6295496d8>

it looks right to me. Please confirm.

``` json
{
    "metricSchemaUrl": "https://api.CHaMPMonitoring.org/api/v1/Visit/metricschemas/QA - Topo Channel Metrics",
    "itemUrl": "https://api.CHaMPMonitoring.org/api/v1/visits/3225",
    "values": [
        {
            "name": "GenerationDate",
            "value": "2017-10-17T17:35:45.055241",
            "type": "String"
        },
        {
            "name": "ModelVersion",
            "value": "0.0.3",
            "type": "String"
        },
        {
            "name": "AreaTotal",
            "value": "15.0159",
            "type": "Numeric"
        },
        {
            "name": "DpthThlwgExit",
            "value": "0.3384",
            "type": "Numeric"
        },
        {
            "name": "ChUnitNumber",
            "value": "13",
            "type": "Numeric"
        },
        {
            "name": "DpthResid",
            "value": "0.0827",
            "type": "Numeric"
        },
        {
            "name": "Dpth_Max",
            "value": "0.4211",
            "type": "Numeric"
        },
        {
            "name": "Tier1",
            "value": "Slow/Pool",
            "type": "String"
        },
        {
            "name": "Tier2",
            "value": "Dam Pool",
            "type": "String"
        },
        {
            "name": "TotalVol",
            "value": "3.526",
            "type": "Numeric"
        }
    ],
    "name": "a12a2ffe-ff83-4ee4-90d7-1ac6295496d8",
    "url": "https://api.CHaMPMonitoring.org/api/v1/Visit/metricschemas/QA - Topo Channel Metrics/metrics/a12a2ffe-ff83-4ee4-90d7-1ac6295496d8"
}
```

**Comment by volkcj** [comment] 2017-10-26 18:22
Ok, here's what I see in the workbench after a fresh pull of this schema.  This looks like a high lob to PB since it looks like the tier 1/tier 2 values are in the API.  The workbench doesn't seem to be pulling these into the QA-Topo Channel Metrics schema for this visit.

![2017-10-26_112115](https://user-images.githubusercontent.com/13526689/32070032-d2a5f892-ba3f-11e7-9b60-274d6370040f.png)

**Comment by philipbaileynar** [comment] 2017-10-30 16:41
I just purged my workbench database of metrics then re-downloaded visit 3225 (the one shown in Carol's screenshot). The tier 1 and tier 2 names appear correctly after metric download.

FYI: The metric plot only works with visit level metrics.

**Closed** 2017-10-30 18:40 UTC
